services:
  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:latest
    container_name: identity_database_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - EMAIL=${EMAIL}
      - PASS_EMAIL=${PASS_EMAIL}
    ports:
      - "5432:5432"
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  your-app:
    build:
      context: .
    image: devhuynh2003/user-server:latest
    container_name: user-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SIGNER_KEY=${SIGNER_KEY}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT={MAIL_PORT}
      - EMAIL=${EMAIL}
      - PASS_EMAIL=${PASS_EMAIL}
    ports:
      - "8080:8080"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  my-postgres-data:
networks:
  app-network:
    driver: bridge